title: Math-For-Fun
author: Oscuro-Phoenix
subtitle: A website to keep a register of the most interesting math problems I've encountered.

url: "/"
baseurl: "oscuro-phoenix.github.io/math-for-fun"

footer_only_homepage: true
footer_url: "https://github.com/Oscuro-Phoenix"
footer_text: ""

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: ""
