title: Math-For-Fun
author: oscuro-phoenix
subtitle: A register of some of the interesting mathematical problems.

url: "https://oscuro-phoenix.github.io"
baseurl: "/math-for-fun"

footer_only_homepage: true
footer_url: "https://github.com/oscuro-phoenix"
footer_text: "Repo"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "LinkedIn Profile"
   absolute-link: "https://www.linkedin.com/in/shakul-pathak-402a6998/"
