title: OCIP
author: oscuro-phoenix
subtitle: Online Compilation of Interesting Problems

url: "https://oscuro-phoenix.github.io"
baseurl: "/math-for-fun"

footer_only_homepage: false
footer_url: "https://www.linkedin.com/company/math-for-fun/"
footer_text: "Follow us on LinkedIn"
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/math-for-fun/

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About the Authors"
   link: "about"
 - name: "Posts"
   absolute-link: "https://oscuro-phoenix.github.io/math-for-fun"
