title: OCIP
author: oscuro-phoenix
subtitle: Online Compilation of Interesting Problems in Mathematics

url: "https://oscuro-phoenix.github.io"
baseurl: "/math-for-fun"

footer_only_homepage: true
footer_url: "https://github.com/oscuro-phoenix"
footer_text: "GitHub Repo"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About the Authors"
   link: "about"
 - name: "Posts"
   absolute-link: "https://oscuro-phoenix.github.io/math-for-fun"
